use super::constants::KtxBaseFormat::*;
use super::constants::KtxDataType::*;
use super::constants::KtxFormat::*;
use super::constants::{KtxBaseFormat, KtxDataType, KtxFormat};

use crate::pixel::PixelFormat;
use crate::pixel::PixelFormat::*;

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub struct KtxMapping {
    pub format: PixelFormat,
    pub internal_format: KtxFormat,
    pub srgb_internal_format: KtxFormat,
    pub base_internal_format: KtxBaseFormat,
    pub data_type: KtxDataType,
}

pub fn get_mapping_for_format<'a>(format: PixelFormat) -> Option<&'a KtxMapping> {
    KTX_MAPPING.iter().find(|&&x| x.format == format)
}

pub fn get_mapping_for_internal_format<'a>(format: KtxFormat) -> Option<&'a KtxMapping> {
    KTX_MAPPING
        .iter()
        .find(|&&x| format == x.srgb_internal_format || format == x.internal_format)
}

// largely lifted from https://github.com/bkaradzic/bimg
// (but not nearly as concise)
const KTX_MAPPING: [KtxMapping; 73] = [
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_S3TC_DXT1_EXT,
        srgb_internal_format: KTX_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_S3TC_DXT3_EXT,
        srgb_internal_format: KTX_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_S3TC_DXT5_EXT,
        srgb_internal_format: KTX_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_LUMINANCE_LATC1_EXT,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_LUMINANCE_ALPHA_LATC2_EXT,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGB_BPTC_SIGNED_FLOAT_ARB,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGB,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_BPTC_UNORM_ARB,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_ETC1_RGB8_OES,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGB,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGB8_ETC2,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGB,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA8_ETC2_EAC,
        srgb_internal_format: KTX_COMPRESSED_SRGB8_ETC2,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2,
        srgb_internal_format: KTX_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGB_PVRTC_2BPPV1_IMG,
        srgb_internal_format: KTX_COMPRESSED_SRGB_PVRTC_2BPPV1_EXT,
        base_internal_format: KTX_RGB,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGB_PVRTC_4BPPV1_IMG,
        srgb_internal_format: KTX_COMPRESSED_SRGB_PVRTC_4BPPV1_EXT,
        base_internal_format: KTX_RGB,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_PVRTC_2BPPV1_IMG,
        srgb_internal_format: KTX_COMPRESSED_SRGB_ALPHA_PVRTC_2BPPV1_EXT,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_PVRTC_4BPPV1_IMG,
        srgb_internal_format: KTX_COMPRESSED_SRGB_ALPHA_PVRTC_4BPPV1_EXT,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_PVRTC_2BPPV2_IMG,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_PVRTC_4BPPV2_IMG,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_ATC_RGB_AMD,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGB,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_ATC_RGBA_EXPLICIT_ALPHA_AMD,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_ATC_RGBA_INTERPOLATED_ALPHA_AMD,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_ASTC_4x4_KHR,
        srgb_internal_format: KTX_COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_ASTC_5x5_KHR,
        srgb_internal_format: KTX_COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_ASTC_6x6_KHR,
        srgb_internal_format: KTX_COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_ASTC_8x5_KHR,
        srgb_internal_format: KTX_COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_ASTC_8x6_KHR,
        srgb_internal_format: KTX_COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_COMPRESSED_RGBA_ASTC_10x5_KHR,
        srgb_internal_format: KTX_COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR,
        base_internal_format: KTX_RGBA,
        data_type: KtxDataType::KTX_NONE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KtxFormat::KTX_ALPHA,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KtxBaseFormat::KTX_ALPHA,
        data_type: KTX_UNSIGNED_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R8,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_UNSIGNED_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R8I,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R8UI,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_UNSIGNED_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R8_SNORM,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R16,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_UNSIGNED_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R16I,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R16UI,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_UNSIGNED_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R16F,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_HALF_FLOAT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R16_SNORM,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R32I,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_INT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R32UI,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_UNSIGNED_INT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R32F,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RED,
        data_type: KTX_FLOAT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG8,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_UNSIGNED_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG8I,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG8UI,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_UNSIGNED_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG8_SNORM,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG16,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_UNSIGNED_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG16I,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG16UI,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_UNSIGNED_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG16F,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_FLOAT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG16_SNORM,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG32I,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_INT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG32UI,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_UNSIGNED_INT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RG32F,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RG,
        data_type: KTX_FLOAT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGB8,
        srgb_internal_format: KTX_SRGB8,
        base_internal_format: KTX_RGB,
        data_type: KTX_UNSIGNED_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGB8I,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGB,
        data_type: KTX_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGB8UI,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGB,
        data_type: KTX_UNSIGNED_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGB8_SNORM,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGB,
        data_type: KTX_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGB9_E5,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGB,
        data_type: KTX_UNSIGNED_INT_5_9_9_9_REV,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA8,
        srgb_internal_format: KTX_SRGB8_ALPHA8,
        base_internal_format: KTX_RGBA,
        data_type: KTX_UNSIGNED_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA8I,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA8UI,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_UNSIGNED_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA8_SNORM,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_BYTE,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA16,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_UNSIGNED_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA16I,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA16UI,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_UNSIGNED_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA16F,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_HALF_FLOAT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA16_SNORM,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_SHORT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA32I,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_INT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA32UI,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_UNSIGNED_INT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA32F,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_FLOAT,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGB565,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGB,
        data_type: KTX_UNSIGNED_SHORT_5_6_5,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGBA4,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_UNSIGNED_SHORT_4_4_4_4,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGB5_A1,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_UNSIGNED_SHORT_5_5_5_1,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_RGB10_A2,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGBA,
        data_type: KTX_UNSIGNED_INT_2_10_10_10_REV,
    },
    KtxMapping {
        format: BC1,
        internal_format: KTX_R11F_G11F_B10F,
        srgb_internal_format: KtxFormat::KTX_NONE,
        base_internal_format: KTX_RGB,
        data_type: KTX_UNSIGNED_INT_10F_11F_11F_REV,
    },
];
